application: azautoscale
productOwner: sarora@mafcarrefour.com
region: uaenorth
productName: azautoscale
services:
  - name: svc
    config:
      category: appservice
      isDockerised: false
      port: 80
      tiersize: P1v2
      stack: JAVA|8-jre8
      envVariables: []
      healthcheck: /health
      serviceType: api
      source: 'https://bitbucket.org/c4hybris/azautoscale' 
