application: azautoscale
productOwner: bahkhan@mafcarrefour.com
region: uaenorth
productName: azautoscale
disableAlerting: true
k8sEnabled: true
services:
  ############## sample COSMOSDB SERVICE ################
          
  - name: "azautoscaledb"
    config:
      category: "cosmosdb"
      location: "uaenorth"
      serviceType: "mongodb"
      consistency: "BoundedStaleness"
      databaseList:
        - azautoscale

  - name: "azautoscale-dev"
    config:
      category: "cache"
      shards: 3
      tiersize: "C0"
      evictionpolicy: "volatile-lru"
      location: "westindia"  

  - name: blob
    config:
      category: blob
      storage: 
        - name: azautoscale-service-dev
          blobType: block
          accessType: blob  
